// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5X4L1iIgFOfooBVAz14K6iloFzoMFMz0',
    appId: '1:66760687862:web:04ded129e491b05317acd7',
    messagingSenderId: '66760687862',
    projectId: 'ecoride-1229d',
    authDomain: 'ecoride-1229d.firebaseapp.com',
    storageBucket: 'ecoride-1229d.firebasestorage.app',
    measurementId: 'G-NYEW474TY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu38Te1S4IDW4gXxjeKd7HW60s8bB-vw0',
    appId: '1:66760687862:android:2b618bf912c6891417acd7',
    messagingSenderId: '66760687862',
    projectId: 'ecoride-1229d',
    storageBucket: 'ecoride-1229d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9IBkpnX4aFXcrx8kqQDb4XUGRxWlbjj8',
    appId: '1:66760687862:ios:a4e560dbb933292c17acd7',
    messagingSenderId: '66760687862',
    projectId: 'ecoride-1229d',
    storageBucket: 'ecoride-1229d.firebasestorage.app',
    iosBundleId: 'com.glider.scooter',
  );
}
