// File generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return ios;
      default:
        return android;
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5X4L1iIgFOfooBVAz14K6iloFzoMFMz0',
    appId: '1:66760687862:web:04ded129e491b05317acd7',
    messagingSenderId: '66760687862',
    projectId: 'ecoride-1229d',
    authDomain: 'ecoride-1229d.firebaseapp.com',
    databaseURL: 'https://ecoride-1229d-default-rtdb.firebaseio.com',
    storageBucket: 'ecoride-1229d.firebasestorage.app',
    measurementId: 'G-NYEW474TY7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9IBkpnX4aFXcrx8kqQDb4XUGRxWlbjj8',
    appId: '1:66760687862:ios:a4e560dbb933292c17acd7',
    messagingSenderId: '66760687862',
    projectId: 'ecoride-1229d',
    databaseURL: 'https://ecoride-1229d-default-rtdb.firebaseio.com',
    storageBucket: 'ecoride-1229d.firebasestorage.app',
    iosClientId:
        '66760687862-0rahmcr0pelkhtlfehuoi3bqm1veemve.apps.googleusercontent.com',
    iosBundleId: 'com.glider.scooter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu38Te1S4IDW4gXxjeKd7HW60s8bB-vw0',
    appId: '1:66760687862:android:2b618bf912c6891417acd7',
    messagingSenderId: '66760687862',
    projectId: 'ecoride-1229d',
    databaseURL: 'https://ecoride-1229d-default-rtdb.firebaseio.com',
    storageBucket: 'ecoride-1229d.firebasestorage.app',
  );
}
